packages:
  - 'apps/*'
  - 'chrome-extensions/*'
  - 'web/*'
  - '!**/test/**'

allowBuilds:
  '@swc/core': true
  esbuild: true
  leveldown: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
