import { defineConfig } from 'rolldown';

export default defineConfig({
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    format: 'cjs',
    entryFileNames: '[name].cjs',
  },
  external: [
    // Node.js 内置模块
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'os',
    'url',
    'util',
    'events',
    'stream',
    'buffer',
    'querystring',
    'zlib',
    'net',
    'tls',
    'child_process',
    'readline',
    'cluster',
    'dgram',
    'dns',
    'domain',
    'module',
    'perf_hooks',
    'punycode',
    'repl',
    'string_decoder',
    'timers',
    'tty',
    'v8',
    'vm',
    'worker_threads',
  ],
});
